name: Deploy to deploy branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to deploy branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout deploy || git checkout -b deploy
          git reset --hard main
          git rm -rf . --quiet
          git checkout main -- dist
          rsync -a dist/ .
          rm -rf dist
          git add .
          git commit -m "Deploy changes" || echo "No changes to deploy"
          git push -f origin deploy
