name: Deploy dist to branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy dist to branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan deploy
          git rm -rf .
          mv dist/* .
          rmdir dist
          git add .
          git commit -m "Deploy build from main"
          git push -f origin deploy
